# TODO: a Deployment that runs 3 replicas of YOUR image; the container serves on port 8080.
# Docs: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clo835-assignment2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: clo835-assignment2
  template:
    metadata:
      labels:
        app: clo835-assignment2
    spec:
      containers:
        - name: nodejs-app
          image: # TODO  e.g. zjlianlee/clo835-assignment2:0.2
          ports:
            - containerPort: 8080
