# TODO: a Service that exposes YOUR app on port 8080 so you can reach it from the host.
# Docs: https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: clo835-assignment2
spec:
  type: NodePort
  selector:
    app: clo835-assignment2
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
